name: card_swiper
description: swiper/carousel for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 3.0.2
homepage: https://github.com/TheAnkurPanchani/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ^3.7.0

dev_dependencies:
  flutter_lints_plus: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
